version: '3.8'

services:
  db:
    image: postgres:15
    container_name: twerlo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    networks:
      - twerlo-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: twerlo-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: chatdb
    networks:
      - twerlo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./client
    container_name: twerlo-client
    ports:
      - "3000:80"
    networks:
      - twerlo-net
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=/api

volumes:
  pgdata:

networks:
  twerlo-net:
    driver: bridge
